name: build

on: [push]

jobs:

  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins --release
      - uses: actions/upload-artifact@v1
        with:
          name: bibfmt
          path: target/release/

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: main-ubuntu-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-macos-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-windows-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-windows-latest
